//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWebApi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ibssrvtest.is.com:15947/DegertAutoBC15/WS/SystemService")]
        public string RestWebApi_Service_Power_BI_Aged_Acc_Receivable_Service {
            get {
                return ((string)(this["RestWebApi_Service_Power_BI_Aged_Acc_Receivable_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ibssrvtest.is.com:15947/DegertAutoBC15/WS/SystemService")]
        public string RestWebApi_Api_System_Service {
            get {
                return ((string)(this["RestWebApi_Api_System_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.161:7517/DeltaPharma2017Final/WS/SystemService")]
        public string RestWebApi_SystemService_SystemService {
            get {
                return ((string)(this["RestWebApi_SystemService_SystemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ibs-server002.is.com:7517/DeltaPharma2017Final/WS/Pas%20Migrimeve-Test/Cod" +
            "eunit/ControlQuantity")]
        public string RestWebApi_Api_ControlQuantity_WebReference_ControlQuantity {
            get {
                return ((string)(this["RestWebApi_Api_ControlQuantity_WebReference_ControlQuantity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ibs-server002.is.com:7517/DeltaPharma2017Final/WS/Pas%20Migrimeve-Test/Page/SalesOrderApi")]
        public string RestWebApi_Api_SalesOrder_WebReference_SalesOrderApi_Service {
            get {
                return ((string)(this["RestWebApi_Api_SalesOrder_WebReference_SalesOrderApi_Service"]));
            }
        }
    }
}
